# This is a basic workflow to help you get started with Actions

name: ProtoGen

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install protoc
        run: |
          chmod +x ./script/install-grpc.sh
          sh ./script/install-grpc.sh
      - name: Convert to Swift
        run: sh ./script/convert-grpc-proto.sh
      - name: Check result
        run: echo `ls ./gRPC`
