# This is a basic workflow to help you get started with Actions

name: ProtoGen

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install protoc
        run: |
          if which protoc >/dev/null; then
            echo "swift-protobuf가 이미 설치되어 있습니다."
          else
            echo "swift-protobuf를 설치합니다."
            brew install swift-protobuf
